### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by nbJosh** [polygontwist/ESP32_32x32RGBMatrix#2]
Gives error "Invalid use of void" in setup()

/Users/joshua/Downloads/ESP32_32x32RGBMatrix/ESP32_32x32RGBMatrix.ino: In function 'void setup()':
ESP32_32x32RGBMatrix:432: error: invalid use of 'void'
     .onEnd([]() {
     ^
/Users/joshua/Downloads/ESP32_32x32RGBMatrix/ESP32_32x32RGBMatrix.ino: In function 'void renderTask(void*)':
ESP32_32x32RGBMatrix:617: error: 'class ESP32RGBmatrixPanel' has no member named 'updateRow'
            matrix.updateRow();//2x16 Zeilen
                   ^
ESP32_32x32RGBMatrix:618: error: 'class ESP32RGBmatrixPanel' has no member named 'updateOn'
            matrix.updateOn();
                   ^

**Comment by nbJosh** [comment]
Looks like the version of ESP32RGBmatrixPanel.cpp and ESP32RGBmatrixPanel.h that I have is not the same as the version you are using,  the version of these files available do not have the functions updateRow, and updateOn

**Comment by polygontwist** [comment]
I had experimented, and the functions briefly built in - but in the current script they are no longer used. delete the function void renderTask(), then it should work.

**Comment by nbJosh** [comment]
Redownloaded and removed that function,  however.

ESP32_32x32RGBMatrix/ESP32_32x32RGBMatrix.ino: In function 'void setup()':
ESP32_32x32RGBMatrix:434: error: invalid use of 'void'
     .onEnd([]() {
     ^
